### ISSUE TITLE
2.2.7 not working, extension page from admin show blank page

### ISSUE THREAD

**Issue by secaliskan** [tigrensolutions/magento2_redis_manager#1]
Hi, 
PHP: 7.0
Version: 2.2.7
Centos 6

after installation with composer backend Redis manager shows only blank white page.
Redis is working at port 6380
cachei paga cache and session is deployed under redis and working without problem,

Please advise,
regards

**Comment by tigrensolutions** [comment]
We've updated our latest code. Please kindly try again.
